spring:
  application:
    name: bet-api
  security:
    user:
      name: admin
      password: secret
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:betdevdb
    driverClassName: org.h2.Driver
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: create