spring:
  application:
    name: bet-api
  security:
    user:
      name: admin
      password: secret
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:betdevdb
    driverClassName: org.h2.Driver
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    active: dev
  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

logging:
  level.org.springframework.security: DEBUG